#pragma once

#include <stdnoreturn.h>

#include "fang_rt/string.h"

void fang_io_print(fang_String const*);

void fang_io_print_int(fang_int);

void fang_io_print_line(void);

/** Read a single character.

    When the input stream is empty, the result is the empty string.
 */
fang_String const* fang_io_read_char(void);

void fang_io_flush(void);

void fang_io_seed_random(fang_int seed);

fang_int fang_io_random(fang_int low, fang_int high);

/** An error generated by a call to error("[...]") in Tiger. */
noreturn void fang_io_tiger_error(fang_String const*);

noreturn void fang_io_exit(fang_int);
