#!/bin/bash

set -x

# See https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html
unset GIT_LITERAL_PATHSPECS

dune clean

#
# From https://stackoverflow.com/questions/20479794/how-do-i-properly-git-stash-pop-in-pre-commit-hooks-to-get-a-clean-working-tree
#

# Look for an old stash, to identify when there are no staged changes.
old_stash=$(git rev-parse -q --verify refs/stash)
git stash push -q --keep-index -m "pre-commit hook"
new_stash=$(git rev-parse -q --verify refs/stash)

# Do nothing if no changes are staged.
if [ "$old_stash" = "$new_stash" ]; then
    exit 0
fi

# All files are formatted correctly and all tests pass.
dune build @fmt && dune test
status=$?

# Restore changes.
git reset --hard -q && git stash apply --index -q && git stash drop -q

exit $status
